apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    version: v1
spec:
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hello
        image: docker.io/josephassiga/ossm-hello-world:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
